volumes:
  fjz-data:
    external: true
services:
  fastapi:
    environment:
      DATABASE_URL: postgresql://fjzllc:fjzapts@db/fjz-data
      WAIT_HOSTS: db:5432
      PORT: 8000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: fjzapts
      POSTGRES_USER: fjzllc
      POSTGRES_DB: fjz-data
    ports:
      - '15432:5432'
    volumes:
      - fjz-data:/var/lib/postgresql
